import db from "../config/db.js";
import { getAuth, requireAuth, clerkClient} from '@clerk/express'

// user signup

export const user_signup = async (req, res)=>{
    try{
    const token = req.headers.authorization?.split(" ")[1];
    console.log("Received token:", token); // Check if token is present and valid
    
    const current_User_Id = req.auth.userId;

    const {fullName, dob, gender} = req.body.data;
    if (!fullName.trim() || !dob || !gender)
    {
        return res.status(400).json({ error: "Backend says missing fields!" }); 
    }
    const result = await db.query(
        `INSERT INTO users (user_id, fullname, dob, gender)
        VALUES ($1, $2, $3, $4) RETURNING *`,
        [current_User_Id, fullName, dob, gender]
      );
      
      const user = result.rows[0];
      console.log("this is our user from our database:",user);

    // everything goes well
    return res.status(200).json({ message: "Authorized" });
    }
    catch(err)
    {
        console.error("Server error during signup",err);
        return res.status(500).json({ error: "Error during signup, Please try again!" });
    }

}

// user PERSONALITY 

export const user_personality = async (req, res)=>{
    console.log("route hit personality wala");
    console.log("answers from personality",req.body);

    // user_personality is generated by the ML model for perssonality


    // everything goes well
    return res.status(200).json({ message: "personality form data submitted" });



    // PERSONALITY ROUTE WILL REMAIN UNTOUCHED UNTIL CLARITY ON PERSONALITY STUFF

    // RESULTING PERSONALITY BASED ON ANSWERS HAS TO BE STORED IN NEW TABLE 
    // WHERE JUST USER ID FROM CLERK AND HIS PERSONALITY WILL BE STORED 
    // FOREIGN KEY USER ID CASCADES

    // sql
    // const user_id = req.auth.userId;
    // const result = await db.query(
    //     `INSERT INTO personality (personality, user_id)
    //     VALUES ($1, $2) RETURNING *`,
    //     [user_personality, user_id]
    //   );
    //   const db_res = result.rows[0];
    //   console.log("current user personality is", db_res.personality);

}

// user SIGN-IN

export const user_signin = async (req, res)=>{
    try{
    console.log("route hit LOGIN wala");
    const userIdd = req.auth.userId;
    const user = await clerkClient.users.getUser(userIdd);
    
    console.log("CURRENT USER:",user);
    
    // everything goes well
    return res.status(200).json({ message: "Login successfull!" });
    }
    catch(err)
    {
        console.error("Server error during login",err);
        return res.status(500).json({ error: "Error during login, Please try again!"});
    }
    
}






